osx_image: xcode10.2
language: objective-c
env:
  global:
    - PROJECT="ios-architecture-example.xcworkspace"
    - IOS_SDK="iphonesimulator"
  matrix:
    - SDK="$IOS_SDK" DESTINATION="platform=iOS Simulator,OS=12.2,name=iPhone X"

before_install:
  - travis_wait pod repo update --silent
  - pod install

install:
  - swift --version

before_script:
  - set -o pipefail

script:
    - xcodebuild clean build
      -workspace "$PROJECT"
      -scheme Shared
      -sdk "$SDK"
      -destination "$DESTINATION" | xcpretty -c
    - xcodebuild clean build
      -workspace "$PROJECT"
      -scheme MVC
      -sdk "$SDK"
      -destination "$DESTINATION" | xcpretty -c
    - xcodebuild clean build
      -workspace "$PROJECT"
      -scheme MVP
      -sdk "$SDK"
      -destination "$DESTINATION" | xcpretty -c
    - xcodebuild clean build
      -workspace "$PROJECT"
      -scheme MVVM-Delegate
      -sdk "$SDK"
      -destination "$DESTINATION" | xcpretty -c
    - xcodebuild clean build
      -workspace "$PROJECT"
      -scheme MVVM-Rx
      -sdk "$SDK"
      -destination "$DESTINATION" | xcpretty -c